### ISSUE TITLE
chosen one

### ISSUE THREAD

**Issue by akivo4ka** [ykomarov94/captain_scrum_bot#2]
`choosen_one` -> `chosen_one`

https://github.com/ykomarov94/captain_scrum_bot/blob/master/main.py#L49

Нет, я не ищу специально очепятки, как могло показаться, я просто добавляю ссылку на гитхаб дисокрд-бота в вики (ну и описание команды !рандом); так что, Юра, страницу `бот дискорд TODO` в wiki у себя в репе можно смело пропустить)

**Comment by ykomarov94** [comment]
@akivo4ka welcome сделать PR с изменением опечатки
